name: PR
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ '**' ]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.7'
      - run: go version
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
     - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1
      - name: Install Dependencies
        run: gem install bundler && bundle install
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Build with Fastlane
        run: fastlane dev
      - name: Run reviewdog
        if: ${{ failure() }}
        continue-on-error: true
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: reviewdog -f=checkstyle -name="ktlint" -reporter=github-pr-review < thredUP/build/reports/ktlint/ktlintMainSourceSetCheck/ktlintMainSourceSetCheck.xml
